version: "3.8"

services:
  hermes-agent:
    image: ghcr.io/sangoisanga/coolify-stacks/hermes-agent:5d5bb37
    container_name: hermes-agent
    command: "gateway run"
    volumes:
      - "hermes-home:/home/hermes/.hermes"
      - "hermes-agent-src:/opt/hermes"
    environment:
      - HERMES_HOME=/home/hermes/.hermes
      - HERMES_UID=1000
      - HERMES_GID=1000
      - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
      - "FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}"
    restart: unless-stopped

volumes:
  hermes-home:
  hermes-agent-src:
